# Generated by Django 5.0.6 on 2024-06-20 13:42

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('slot_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand_images/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='child_sub_category_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('include_in_navigation_menu', models.BooleanField(default=True)),
                ('slot_position', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parent_category_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('include_in_navigation_menu', models.BooleanField(default=True)),
                ('slot_position', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('slot_position', models.IntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('simple', 'simple'), ('variation', 'variation'), ('variable', 'variable'), ('Grouped', 'Grouped'), ('External', 'External')], max_length=20)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('published', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Private', 'Private')], max_length=20)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_stock', models.CharField(choices=[('Instock', 'Instock'), ('Outofstock', 'Outofstock')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_amount', models.PositiveIntegerField(default=0)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allow_customer_reviews', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('new_arrivals', models.BooleanField(default=False)),
                ('best_seller', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('brands', models.ManyToManyField(blank=True, to='product.brand')),
                ('categories', models.ManyToManyField(blank=True, to='product.parentcategory')),
                ('childsubcategories', models.ManyToManyField(blank=True, to='product.childsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CrossSellProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('cross_sell_products', models.ManyToManyField(related_name='cross_sell_products', to='product.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ComboProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('Combo_products', models.ManyToManyField(related_name='ComboProduct', to='product.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.product_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('slot_position', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_category_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('include_in_navigation_menu', models.BooleanField(default=True)),
                ('slot_position', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('skin_routine', models.BooleanField(default=False)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.parentcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='childsubcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='product.tag'),
        ),
        migrations.CreateModel(
            name='UpsellProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('upsell_products', models.ManyToManyField(related_name='upsell_products', to='product.product')),
            ],
        ),
    ]
