# Generated by Django 5.0.6 on 2024-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="slot_position",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
