# Generated by Django 5.0.6 on 2024-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0002_pricebanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="why_us/")),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
