# Generated by Django 5.0.6 on 2024-06-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0003_whyus"),
    ]

    operations = [
        migrations.AddField(
            model_name="whyus",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
