# Generated by Django 5.0.6 on 2024-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_whyus_slot_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricebanner',
            name='Category',
        ),
        migrations.AlterField(
            model_name='footerbanner',
            name='banner_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='banner_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pricebanner',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
