# Generated by Django 5.0.6 on 2024-06-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('discount_type', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=20)),
                ('coupon_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allow_free_shipping', models.BooleanField(default=False)),
                ('coupon_start_date', models.DateField()),
                ('coupon_end_date', models.DateField()),
                ('minimum_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('individual_use_only', models.BooleanField(default=False)),
                ('exclude_sale_items', models.BooleanField(default=False)),
                ('allowed_emails', models.TextField(blank=True)),
                ('usage_limit_per_coupon', models.PositiveIntegerField(default=0)),
                ('limit_usage_to_x_items', models.PositiveIntegerField(default=0)),
                ('usage_limit_per_user', models.PositiveIntegerField(default=0)),
                ('exclude_categories', models.ManyToManyField(blank=True, related_name='excluded_coupon_categories', to='product.childsubcategory')),
                ('exclude_products', models.ManyToManyField(blank=True, related_name='excluded_coupon_products', to='product.product')),
                ('product_categories', models.ManyToManyField(blank=True, related_name='coupon_product_categories', to='product.childsubcategory')),
                ('products', models.ManyToManyField(blank=True, related_name='coupon_products', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
            ],
        ),
    ]
