# Generated by Django 5.0.6 on 2024-07-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0002_initial"),
        ("product", "0002_alter_productimage_slot_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="exclude_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="excluded_coupon_categories",
                to="product.parentcategory",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="product_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="coupon_product_categories",
                to="product.parentcategory",
            ),
        ),
    ]
