# Generated by Django 5.0.6 on 2024-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0003_alter_coupon_exclude_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="limit_usage_to_x_items",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit_per_coupon",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit_per_user",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
