# Generated by Django 5.0.6 on 2024-07-01 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_okdusers_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okdusers',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
