# Generated by Django 5.0.6 on 2024-06-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=100)),
                ('from_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('delivery_date', models.DateField()),
                ('email_design_id', models.IntegerField()),
                ('gift_card_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftcard.giftcard')),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.orderitem')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('redeemed', 'Redeemed'), ('refunded', 'Refunded')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('reference_activity_id', models.IntegerField()),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.giftcard')),
            ],
        ),
    ]
