# Generated by Django 5.0.6 on 2024-07-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="track_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
